require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const User = require('../models/User');
const Department = require('../models/Department');
const Employee = require('../models/Employee');
const Vendor = require('../models/Vendor');
const Customer = require('../models/Customer');
const BankAccount = require('../models/BankAccount');
const Budget = require('../models/Budget');
const Invoice = require('../models/Invoice');
const Transaction = require('../models/Transaction');
const FraudAlert = require('../models/FraudAlert');
const Investigation = require('../models/Investigation');
const AuditLog = require('../models/AuditLog');

const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/finguard_ai';
    await mongoose.connect(mongoUri);
    console.log('[Seed Engine] Connected to MongoDB database:', mongoUri);

    // Clear existing collections
    await Promise.all([
      User.deleteMany({}),
      Department.deleteMany({}),
      Employee.deleteMany({}),
      Vendor.deleteMany({}),
      Customer.deleteMany({}),
      BankAccount.deleteMany({}),
      Budget.deleteMany({}),
      Invoice.deleteMany({}),
      Transaction.deleteMany({}),
      FraudAlert.deleteMany({}),
      Investigation.deleteMany({}),
      AuditLog.deleteMany({}),
    ]);
    console.log('[Seed Engine] Cleared existing records.');

    // 1. Seed Users (Covering all 6 RBAC roles)
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash('FinGuard2026!', salt);

    const usersData = [
      {
        name: 'Alex Vance',
        email: 'alex.vance@finguard.internal',
        password: hashedPassword,
        role: 'Owner',
        department: 'Executive',
        title: 'Chief Financial Officer',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      },
      {
        name: 'Elena Rostova',
        email: 'elena.rostova@finguard.internal',
        password: hashedPassword,
        role: 'Fraud Analyst',
        department: 'Security & Risk',
        title: 'Lead Forensic Risk Analyst',
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      },
      {
        name: 'Marcus Sterling',
        email: 'marcus.sterling@finguard.internal',
        password: hashedPassword,
        role: 'Finance Manager',
        department: 'Finance',
        title: 'Director of Corporate Treasury',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      },
      {
        name: 'Sarah Chen',
        email: 'sarah.chen@finguard.internal',
        password: hashedPassword,
        role: 'Accountant',
        department: 'Finance',
        title: 'Senior Financial Controller',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      },
      {
        name: 'David Kim',
        email: 'david.kim@finguard.internal',
        password: hashedPassword,
        role: 'Department Manager',
        department: 'Engineering',
        title: 'VP of Engineering',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      },
      {
        name: 'Jessica Miller',
        email: 'jessica.miller@finguard.internal',
        password: hashedPassword,
        role: 'Employee',
        department: 'Sales & Marketing',
        title: 'Account Executive',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      },
    ];

    const users = await User.insertMany(usersData);
    console.log(`[Seed Engine] Created ${users.length} Users with RBAC permissions.`);

    // 2. Seed Departments
    const departmentsData = [
      {
        name: 'Engineering',
        code: 'ENG',
        managerName: 'David Kim',
        managerEmail: 'david.kim@finguard.internal',
        allocatedBudget: 350000,
        currentSpend: 312400,
        riskExposure: 14500,
        headcount: 28,
        color: '#3B82F6',
      },
      {
        name: 'Sales & Marketing',
        code: 'MKT',
        managerName: 'Rachel Green',
        managerEmail: 'rachel.green@finguard.internal',
        allocatedBudget: 220000,
        currentSpend: 238900, // Over budget!
        riskExposure: 28400,
        headcount: 18,
        color: '#EC4899',
      },
      {
        name: 'Operations & IT',
        code: 'OPS',
        managerName: 'Robert Lang',
        managerEmail: 'robert.lang@finguard.internal',
        allocatedBudget: 180000,
        currentSpend: 154200,
        riskExposure: 8200,
        headcount: 14,
        color: '#10B981',
      },
      {
        name: 'Product & Design',
        code: 'PRD',
        managerName: 'Amina Idris',
        managerEmail: 'amina.idris@finguard.internal',
        allocatedBudget: 140000,
        currentSpend: 112000,
        riskExposure: 0,
        headcount: 11,
        color: '#8B5CF6',
      },
      {
        name: 'Legal & Compliance',
        code: 'LGL',
        managerName: 'Harrison Ford',
        managerEmail: 'harrison.ford@finguard.internal',
        allocatedBudget: 95000,
        currentSpend: 81500,
        riskExposure: 0,
        headcount: 6,
        color: '#F59E0B',
      },
      {
        name: 'Human Resources',
        code: 'HR',
        managerName: 'Claire Bennett',
        managerEmail: 'claire.bennett@finguard.internal',
        allocatedBudget: 80000,
        currentSpend: 67300,
        riskExposure: 4900,
        headcount: 8,
        color: '#06B6D4',
      },
    ];

    const departments = await Department.insertMany(departmentsData);
    console.log(`[Seed Engine] Created ${departments.length} Departments.`);

    // 3. Seed Bank Accounts
    const bankAccountsData = [
      {
        accountName: 'Operating Treasury',
        accountNumber: '•••• 8901',
        bankName: 'J.P. Morgan Chase Commercial',
        accountType: 'Checking',
        currency: 'USD',
        currentBalance: 1485600,
        availableBalance: 1420000,
        routingNumber: '021000021',
        status: 'Active',
      },
      {
        accountName: 'High-Yield Liquid Reserves',
        accountNumber: '•••• 4419',
        bankName: 'Charles Schwab Institutional',
        accountType: 'Treasury',
        currency: 'USD',
        currentBalance: 850000,
        availableBalance: 850000,
        routingNumber: '121000358',
        status: 'Active',
      },
      {
        accountName: 'Payroll Clearing Account',
        accountNumber: '•••• 7723',
        bankName: 'Silicon Valley Bank (First Citizens)',
        accountType: 'Payroll',
        currency: 'USD',
        currentBalance: 285400,
        availableBalance: 285400,
        routingNumber: '121140399',
        status: 'Active',
      },
      {
        accountName: 'Merchant Settlements & Escrow',
        accountNumber: '•••• 1092',
        bankName: 'Citibank Commercial Services',
        accountType: 'Escrow',
        currency: 'USD',
        currentBalance: 165800,
        availableBalance: 165800,
        routingNumber: '021000089',
        status: 'Active',
      },
    ];

    const bankAccounts = await BankAccount.insertMany(bankAccountsData);
    console.log(`[Seed Engine] Created ${bankAccounts.length} Bank Accounts.`);

    // 4. Seed Employees
    const employeesData = [
      {
        employeeId: 'EMP-0101',
        name: 'David Kim',
        email: 'david.kim@finguard.internal',
        department: 'Engineering',
        role: 'VP of Engineering',
        monthlySpendLimit: 25000,
        currentMonthSpend: 18400,
        totalClaimsCount: 14,
        averageClaimAmount: 1314,
        riskScore: 8,
        riskLevel: 'Low',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      },
      {
        employeeId: 'EMP-0102',
        name: 'Rachel Green',
        email: 'rachel.green@finguard.internal',
        department: 'Sales & Marketing',
        role: 'VP of Marketing',
        monthlySpendLimit: 20000,
        currentMonthSpend: 24500, // Over limit
        totalClaimsCount: 22,
        averageClaimAmount: 1113,
        riskScore: 42,
        riskLevel: 'Medium',
        flags: ['Monthly spending ceiling exceeded by $4,500'],
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      },
      {
        employeeId: 'EMP-0103',
        name: 'Jessica Miller',
        email: 'jessica.miller@finguard.internal',
        department: 'Sales & Marketing',
        role: 'Senior Account Executive',
        monthlySpendLimit: 6000,
        currentMonthSpend: 5850,
        totalClaimsCount: 18,
        averageClaimAmount: 325,
        riskScore: 14,
        riskLevel: 'Low',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      },
      {
        employeeId: 'EMP-0104',
        name: 'Jonathan Reynolds',
        email: 'jonathan.reynolds@finguard.internal',
        department: 'Engineering',
        role: 'Principal Cloud Architect',
        monthlySpendLimit: 15000,
        currentMonthSpend: 14200,
        totalClaimsCount: 9,
        averageClaimAmount: 1577,
        riskScore: 22,
        riskLevel: 'Low',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      },
      {
        employeeId: 'EMP-0105',
        name: 'Bradley Cooper',
        email: 'bradley.cooper@finguard.internal',
        department: 'Operations & IT',
        role: 'IT Procurement Manager',
        monthlySpendLimit: 10000,
        currentMonthSpend: 9800,
        totalClaimsCount: 16,
        averageClaimAmount: 612,
        riskScore: 68, // High risk (structured expenses)
        riskLevel: 'High',
        flags: ['Consecutive submissions immediately under $5,000 threshold'],
        avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      },
      {
        employeeId: 'EMP-0106',
        name: 'Sophia Laurent',
        email: 'sophia.laurent@finguard.internal',
        department: 'Product & Design',
        role: 'Design Director',
        monthlySpendLimit: 8000,
        currentMonthSpend: 4200,
        totalClaimsCount: 8,
        averageClaimAmount: 525,
        riskScore: 10,
        riskLevel: 'Low',
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      },
      {
        employeeId: 'EMP-0107',
        name: 'Claire Bennett',
        email: 'claire.bennett@finguard.internal',
        department: 'Human Resources',
        role: 'Head of People',
        monthlySpendLimit: 10000,
        currentMonthSpend: 6800,
        totalClaimsCount: 12,
        averageClaimAmount: 566,
        riskScore: 9,
        riskLevel: 'Low',
        avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
      },
      {
        employeeId: 'EMP-0108',
        name: 'Marcus Sterling',
        email: 'marcus.sterling@finguard.internal',
        department: 'Finance',
        role: 'Treasury Director',
        monthlySpendLimit: 50000,
        currentMonthSpend: 31200,
        totalClaimsCount: 15,
        averageClaimAmount: 2080,
        riskScore: 12,
        riskLevel: 'Low',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      },
    ];

    const employees = await Employee.insertMany(employeesData);
    console.log(`[Seed Engine] Created ${employees.length} Employees.`);

    // 5. Seed 16 Vendors
    const vendorsData = [
      {
        vendorId: 'VND-101',
        name: 'Amazon Web Services Inc.',
        category: 'Cloud Infrastructure',
        contactEmail: 'billing@aws.amazon.internal',
        contactPhone: '+1 (800) 222-0941',
        address: '410 Terry Ave N, Seattle, WA',
        bankAccount: '•••• 9012',
        bankRouting: '021000021',
        bankName: 'JPMorgan Chase',
        taxId: 'XX-XXX4192',
        paymentTerms: 'Net 30',
        totalSpending: 214500,
        transactionCount: 18,
        avgTransaction: 11916,
        riskScore: 6,
        riskLevel: 'Low',
        status: 'Active',
        historicalBaselineSpend: 11500,
        recentSpendSpikeRatio: 1.05,
      },
      {
        vendorId: 'VND-102',
        name: 'NovaTech Digital Solutions',
        category: 'IT Consulting & Hardware',
        contactEmail: 'ar@novatech-solutions.fake',
        contactPhone: '+1 (415) 882-9901',
        address: '500 Howard St, San Francisco, CA',
        bankAccount: '•••• 6671', // Recently altered bank details!
        bankRouting: '121000358',
        bankName: 'Wells Fargo Commercial',
        taxId: 'XX-XXX8812',
        paymentTerms: 'Net 15',
        totalSpending: 89400,
        transactionCount: 6,
        avgTransaction: 14900,
        riskScore: 88, // CRITICAL RISK VENDOR
        riskLevel: 'Critical',
        status: 'Flagged',
        accountDetailsLastModified: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000), // 4 days ago
        historicalBaselineSpend: 4200,
        recentSpendSpikeRatio: 3.55,
        riskFactors: [
          'Bank account and routing coordinates changed 4 days ago without dual-signoff',
          'Invoice amount spike: 3.55x above 90-day baseline average',
          'Execution timestamp recorded at 02:41 AM on a Sunday',
        ],
        aiVendorSummary: 'CRITICAL ALERT: Banking credentials modified on Oct 1st. Single invoice amount ($34,800) is drastically higher than historical supplier average ($4,200).',
      },
      {
        vendorId: 'VND-103',
        name: 'Apex Cloud Systems LLC',
        category: 'DevOps & Tooling',
        contactEmail: 'invoices@apexcloud.internal',
        contactPhone: '+1 (206) 441-9923',
        address: '1200 5th Ave, Seattle, WA',
        bankAccount: '•••• 3341',
        bankRouting: '021000089',
        bankName: 'Citi Commercial',
        taxId: 'XX-XXX3311',
        paymentTerms: 'Net 30',
        totalSpending: 72500,
        transactionCount: 8,
        avgTransaction: 9062,
        riskScore: 82, // High risk duplicate payment
        riskLevel: 'Critical',
        status: 'Under Review',
        hasDuplicateInvoices: true,
        riskFactors: [
          'Duplicate billing identified: $14,500 invoiced twice within 48 hours with identical reference numbers',
        ],
        aiVendorSummary: 'Duplicate invoice collision detected against PO-4921. Secondary batch payment queued for settlement freeze.',
      },
      {
        vendorId: 'VND-104',
        name: 'Datadog Inc.',
        category: 'Software & SaaS',
        contactEmail: 'accounts@datadoghq.com',
        contactPhone: '+1 (866) 329-4466',
        address: '620 8th Ave, New York, NY',
        bankAccount: '•••• 1120',
        bankRouting: '021000021',
        bankName: 'JPMorgan Chase',
        paymentTerms: 'Net 30',
        totalSpending: 64200,
        transactionCount: 12,
        avgTransaction: 5350,
        riskScore: 8,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-105',
        name: 'Vanguard Media & Growth',
        category: 'Marketing & Advertising',
        contactEmail: 'finance@vanguardmedia.agency',
        contactPhone: '+1 (310) 554-1029',
        address: '8800 Wilshire Blvd, Beverly Hills, CA',
        bankAccount: '•••• 5590',
        bankRouting: '122000496',
        bankName: 'Bank of America',
        paymentTerms: 'Net 30',
        totalSpending: 94800,
        transactionCount: 7,
        avgTransaction: 13542,
        riskScore: 65, // High risk spend spike
        riskLevel: 'High',
        status: 'Under Review',
        historicalBaselineSpend: 4500,
        recentSpendSpikeRatio: 3.1,
        riskFactors: ['Expenditures accelerated 3.1x over 30 days without associated marketing budget increase'],
      },
      {
        vendorId: 'VND-106',
        name: 'Google Workspace & Cloud',
        category: 'Software & SaaS',
        contactEmail: 'google-payments@google.com',
        contactPhone: '+1 (650) 253-0000',
        address: '1600 Amphitheatre Pkwy, Mountain View, CA',
        bankAccount: '•••• 4410',
        bankRouting: '121000358',
        bankName: 'Wells Fargo',
        paymentTerms: 'Net 30',
        totalSpending: 38400,
        transactionCount: 12,
        avgTransaction: 3200,
        riskScore: 5,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-107',
        name: 'Covington & Burling LLP',
        category: 'Legal & Professional',
        contactEmail: 'ap@cov.com',
        contactPhone: '+1 (202) 662-6000',
        address: '850 Tenth St NW, Washington, DC',
        bankAccount: '•••• 9981',
        bankRouting: '021000089',
        bankName: 'Citibank',
        paymentTerms: 'Net 45',
        totalSpending: 82000,
        transactionCount: 5,
        avgTransaction: 16400,
        riskScore: 12,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-108',
        name: 'WeWork Global Spaces',
        category: 'Facilities & Rent',
        contactEmail: 'realestate@wework.com',
        contactPhone: '+1 (888) 977-4184',
        address: '575 Lexington Ave, New York, NY',
        bankAccount: '•••• 7761',
        bankRouting: '021000021',
        bankName: 'JPMorgan Chase',
        paymentTerms: 'Net 15',
        totalSpending: 145000,
        transactionCount: 10,
        avgTransaction: 14500,
        riskScore: 10,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-109',
        name: 'Kroll Cyber Security',
        category: 'Security & Audit',
        contactEmail: 'billing@kroll.com',
        contactPhone: '+1 (212) 593-1000',
        address: '55 E 52nd St, New York, NY',
        bankAccount: '•••• 3312',
        bankRouting: '021000089',
        bankName: 'Citibank',
        paymentTerms: 'Net 30',
        totalSpending: 48500,
        transactionCount: 3,
        avgTransaction: 16166,
        riskScore: 14,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-110',
        name: 'Pivotal Talent Recruitment',
        category: 'Human Resources',
        contactEmail: 'finance@pivotalrecruiting.com',
        contactPhone: '+1 (415) 779-1120',
        address: '100 Montgomery St, San Francisco, CA',
        bankAccount: '•••• 8820',
        bankRouting: '121000358',
        bankName: 'Wells Fargo',
        paymentTerms: 'Net 30',
        totalSpending: 52000,
        transactionCount: 4,
        avgTransaction: 13000,
        riskScore: 18,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-111',
        name: 'Stripe Corporate Billing',
        category: 'Financial Services',
        contactEmail: 'support@stripe.com',
        contactPhone: '+1 (888) 926-2289',
        address: '354 Oyster Point Blvd, South San Francisco, CA',
        bankAccount: '•••• 1009',
        bankRouting: '121140399',
        bankName: 'SVB',
        paymentTerms: 'Immediate',
        totalSpending: 31200,
        transactionCount: 15,
        avgTransaction: 2080,
        riskScore: 6,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-112',
        name: 'Catering & Executive Events Co',
        category: 'Office & Hospitality',
        contactEmail: 'orders@executiveevents.internal',
        contactPhone: '+1 (415) 332-9011',
        address: '220 4th St, San Francisco, CA',
        bankAccount: '•••• 4432',
        bankRouting: '121000358',
        bankName: 'Wells Fargo',
        paymentTerms: 'Net 15',
        totalSpending: 18400,
        transactionCount: 9,
        avgTransaction: 2044,
        riskScore: 15,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-113',
        name: 'Iron Mountain Archiving',
        category: 'Compliance & Storage',
        contactEmail: 'billing@ironmountain.com',
        contactPhone: '+1 (800) 899-4766',
        address: '1 Federal St, Boston, MA',
        bankAccount: '•••• 6650',
        bankRouting: '021000021',
        bankName: 'Chase',
        paymentTerms: 'Net 30',
        totalSpending: 12800,
        transactionCount: 6,
        avgTransaction: 2133,
        riskScore: 8,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-114',
        name: 'Slack Technologies',
        category: 'Software & SaaS',
        contactEmail: 'billing@slack.com',
        contactPhone: '+1 (415) 630-7943',
        address: '500 Howard St, San Francisco, CA',
        bankAccount: '•••• 1982',
        bankRouting: '121000358',
        bankName: 'Wells Fargo',
        paymentTerms: 'Net 30',
        totalSpending: 24600,
        transactionCount: 6,
        avgTransaction: 4100,
        riskScore: 5,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-115',
        name: 'FedEx Corporate Logistics',
        category: 'Logistics & Shipping',
        contactEmail: 'invoicing@fedex.com',
        contactPhone: '+1 (800) 463-3339',
        address: '942 S Shady Grove Rd, Memphis, TN',
        bankAccount: '•••• 7712',
        bankRouting: '084000026',
        bankName: 'First Horizon',
        paymentTerms: 'Net 30',
        totalSpending: 14200,
        transactionCount: 12,
        avgTransaction: 1183,
        riskScore: 9,
        riskLevel: 'Low',
        status: 'Active',
      },
      {
        vendorId: 'VND-116',
        name: 'Global Executive Travel Corp',
        category: 'Travel & Lodging',
        contactEmail: 'reservations@globalexec-travel.fake',
        contactPhone: '+1 (212) 880-1922',
        address: '350 5th Ave, New York, NY',
        bankAccount: '•••• 9940',
        bankRouting: '021000089',
        bankName: 'Citi',
        paymentTerms: 'Immediate',
        totalSpending: 42800,
        transactionCount: 8,
        avgTransaction: 5350,
        riskScore: 58, // Medium-High risk employee travel charges
        riskLevel: 'Medium',
        status: 'Active',
        riskFactors: ['Repeated luxury weekend travel claims exceeding standard per-diem policy'],
      },
    ];

    const vendors = await Vendor.insertMany(vendorsData);
    console.log(`[Seed Engine] Created ${vendors.length} Vendors.`);

    // 6. Seed Customers
    const customersData = [
      {
        customerId: 'CUST-301',
        name: 'CyberScale Corp',
        company: 'CyberScale Networks Inc',
        email: 'ap@cyberscale.com',
        phone: '+1 (415) 992-1200',
        creditLimit: 150000,
        outstandingBalance: 68400,
        paymentTerms: 'Net 30',
        averageDaysToPay: 24,
        riskScore: 12,
        status: 'Active',
      },
      {
        customerId: 'CUST-302',
        name: 'Horizon FinTech Group',
        company: 'Horizon Global Payments LLC',
        email: 'treasury@horizonfintech.com',
        phone: '+1 (212) 554-0980',
        creditLimit: 250000,
        outstandingBalance: 124500,
        paymentTerms: 'Net 45',
        averageDaysToPay: 42,
        riskScore: 28,
        status: 'Active',
      },
      {
        customerId: 'CUST-303',
        name: 'Aether BioSystems',
        company: 'Aether Therapeutics Ltd',
        email: 'billing@aetherbio.com',
        creditLimit: 80000,
        outstandingBalance: 42800, // Overdue
        paymentTerms: 'Net 30',
        averageDaysToPay: 64,
        riskScore: 62,
        status: 'Delinquent',
      },
      {
        customerId: 'CUST-304',
        name: 'Nexus Dynamics',
        company: 'Nexus Robotics AI Corp',
        email: 'accounts@nexusdynamics.io',
        creditLimit: 120000,
        outstandingBalance: 31200,
        paymentTerms: 'Net 30',
        averageDaysToPay: 21,
        riskScore: 8,
        status: 'Active',
      },
      {
        customerId: 'CUST-305',
        name: 'Silverline Media',
        company: 'Silverline Interactive Inc',
        email: 'finance@silverline.media',
        creditLimit: 60000,
        outstandingBalance: 18500,
        paymentTerms: 'Net 30',
        averageDaysToPay: 31,
        riskScore: 15,
        status: 'Active',
      },
      {
        customerId: 'CUST-306',
        name: 'Vortex Capital Partners',
        company: 'Vortex Investment Fund IV',
        email: 'accounting@vortexcap.com',
        creditLimit: 300000,
        outstandingBalance: 88000,
        paymentTerms: 'Net 45',
        averageDaysToPay: 29,
        riskScore: 10,
        status: 'Active',
      },
      {
        customerId: 'CUST-307',
        name: 'Quantum Logic Systems',
        company: 'Quantum Logic Software AG',
        email: 'invoicing@quantumlogic.de',
        creditLimit: 90000,
        outstandingBalance: 24800,
        paymentTerms: 'Net 30',
        averageDaysToPay: 27,
        riskScore: 14,
        status: 'Active',
      },
      {
        customerId: 'CUST-308',
        name: 'Solaria Energy Technologies',
        company: 'Solaria Solar Grids Inc',
        email: 'ap@solariagrid.com',
        creditLimit: 100000,
        outstandingBalance: 54000,
        paymentTerms: 'Net 60',
        averageDaysToPay: 55,
        riskScore: 35,
        status: 'Active',
      },
    ];

    const customers = await Customer.insertMany(customersData);
    console.log(`[Seed Engine] Created ${customers.length} Customers.`);

    // 7. Seed Budgets
    const budgetsData = [
      {
        department: 'Engineering',
        fiscalYear: 2026,
        quarter: 'Q3',
        allocatedAmount: 350000,
        actualSpent: 312400,
        committedAmount: 22000,
        alertThresholdPercent: 85,
        status: 'Near Limit',
        notes: 'Accelerated cloud compute provisioning for EU data residency compliance.',
      },
      {
        department: 'Sales & Marketing',
        fiscalYear: 2026,
        quarter: 'Q3',
        allocatedAmount: 220000,
        actualSpent: 238900,
        committedAmount: 15000,
        alertThresholdPercent: 85,
        status: 'Over Budget',
        notes: 'Overrun caused by unbudgeted Q3 keynote sponsorship and search ad surges.',
      },
      {
        department: 'Operations & IT',
        fiscalYear: 2026,
        quarter: 'Q3',
        allocatedAmount: 180000,
        actualSpent: 154200,
        committedAmount: 12000,
        alertThresholdPercent: 85,
        status: 'Near Limit',
        notes: 'New employee workstation hardware batch acquisition.',
      },
      {
        department: 'Product & Design',
        fiscalYear: 2026,
        quarter: 'Q3',
        allocatedAmount: 140000,
        actualSpent: 112000,
        committedAmount: 8000,
        alertThresholdPercent: 85,
        status: 'Healthy',
        notes: 'On track with Q3 design systems revamp.',
      },
      {
        department: 'Legal & Compliance',
        fiscalYear: 2026,
        quarter: 'Q3',
        allocatedAmount: 95000,
        actualSpent: 81500,
        committedAmount: 5000,
        alertThresholdPercent: 85,
        status: 'Healthy',
        notes: 'Retainer fees for annual SOC2 Type II certification.',
      },
      {
        department: 'Human Resources',
        fiscalYear: 2026,
        quarter: 'Q3',
        allocatedAmount: 80000,
        actualSpent: 67300,
        committedAmount: 4000,
        alertThresholdPercent: 85,
        status: 'Healthy',
        notes: 'Annual employee health & benefits enrollment platform renewal.',
      },
    ];

    const budgets = await Budget.insertMany(budgetsData);
    console.log(`[Seed Engine] Created ${budgets.length} Budgets.`);

    // 8. Seed Invoices (both Receivables and Payables)
    const invoicesData = [
      // Receivables
      {
        invoiceNumber: 'INV-2026-1001',
        type: 'receivable',
        customerName: 'CyberScale Corp',
        department: 'Sales',
        issueDate: new Date('2026-08-15'),
        dueDate: new Date('2026-09-15'), // Overdue 18 days
        items: [
          { description: 'FinGuard Enterprise AI Platform - Tier 1 Annual License', quantity: 1, unitPrice: 48000, amount: 48000 },
          { description: 'Premium 24/7 Dedicated Support SLA', quantity: 1, unitPrice: 12000, amount: 12000 },
        ],
        subtotal: 60000,
        tax: 4800,
        totalAmount: 64800,
        amountPaid: 0,
        balanceDue: 64800,
        status: 'overdue',
        paymentTerms: 'Net 30',
        paymentHistory: [],
      },
      {
        invoiceNumber: 'INV-2026-1002',
        type: 'receivable',
        customerName: 'Horizon FinTech Group',
        department: 'Sales',
        issueDate: new Date('2026-09-01'),
        dueDate: new Date('2026-10-15'),
        items: [
          { description: 'Fraud Detection Engine API Integration (Quarterly)', quantity: 3, unitPrice: 28000, amount: 84000 },
        ],
        subtotal: 84000,
        tax: 6720,
        totalAmount: 90720,
        amountPaid: 45000,
        balanceDue: 45720,
        status: 'partially_paid',
        paymentTerms: 'Net 45',
        paymentHistory: [{ paymentDate: new Date('2026-09-20'), amount: 45000, method: 'Wire Transfer', reference: 'WT-88192' }],
      },
      {
        invoiceNumber: 'INV-2026-1003',
        type: 'receivable',
        customerName: 'Aether BioSystems',
        department: 'Sales',
        issueDate: new Date('2026-06-20'),
        dueDate: new Date('2026-07-20'), // 70+ days overdue
        items: [{ description: 'Custom Machine Learning Anomaly Pipeline Setup', quantity: 1, unitPrice: 38000, amount: 38000 }],
        subtotal: 38000,
        tax: 3040,
        totalAmount: 41040,
        amountPaid: 0,
        balanceDue: 41040,
        status: 'overdue',
        paymentTerms: 'Net 30',
      },
      {
        invoiceNumber: 'INV-2026-1004',
        type: 'receivable',
        customerName: 'Nexus Dynamics',
        department: 'Sales',
        issueDate: new Date('2026-09-18'),
        dueDate: new Date('2026-10-18'),
        items: [{ description: 'Corporate Finance Telemetry Connector', quantity: 1, unitPrice: 28500, amount: 28500 }],
        subtotal: 28500,
        tax: 2280,
        totalAmount: 30780,
        amountPaid: 30780,
        balanceDue: 0,
        status: 'paid',
        paymentTerms: 'Net 30',
        paymentHistory: [{ paymentDate: new Date('2026-09-25'), amount: 30780, method: 'ACH', reference: 'ACH-44102' }],
      },
      {
        invoiceNumber: 'INV-2026-1005',
        type: 'receivable',
        customerName: 'Vortex Capital Partners',
        department: 'Sales',
        issueDate: new Date('2026-09-10'),
        dueDate: new Date('2026-10-25'),
        items: [{ description: 'Automated Portfolio Risk Surveillance Module', quantity: 1, unitPrice: 75000, amount: 75000 }],
        subtotal: 75000,
        tax: 6000,
        totalAmount: 81000,
        amountPaid: 0,
        balanceDue: 81000,
        status: 'sent',
        paymentTerms: 'Net 45',
      },
      // Payables
      {
        invoiceNumber: 'INV-2026-2001',
        type: 'payable',
        vendorName: 'Amazon Web Services Inc.',
        department: 'Engineering',
        issueDate: new Date('2026-09-02'),
        dueDate: new Date('2026-10-02'),
        items: [{ description: 'AWS Cloud Hosting - September Usage', quantity: 1, unitPrice: 16800, amount: 16800 }],
        subtotal: 16800,
        tax: 0,
        totalAmount: 16800,
        amountPaid: 0,
        balanceDue: 16800,
        status: 'sent',
        paymentTerms: 'Net 30',
      },
      {
        invoiceNumber: 'INV-2026-2002',
        type: 'payable',
        vendorName: 'NovaTech Digital Solutions',
        department: 'Engineering',
        issueDate: new Date('2026-09-28'),
        dueDate: new Date('2026-10-12'),
        items: [
          { description: 'Data Center Hardware Acceleration Nodes', quantity: 2, unitPrice: 17400, amount: 34800 },
        ],
        subtotal: 34800,
        tax: 0,
        totalAmount: 34800,
        amountPaid: 0,
        balanceDue: 34800,
        status: 'disputed', // Critical fraud alert attached
        riskScore: 88,
        riskLevel: 'Critical',
        riskFactors: ['Suspicious vendor routing change', '3.5x spending surge'],
        paymentTerms: 'Net 15',
      },
      {
        invoiceNumber: 'INV-2026-2003',
        type: 'payable',
        vendorName: 'Apex Cloud Systems LLC',
        department: 'Engineering',
        issueDate: new Date('2026-09-26'),
        dueDate: new Date('2026-10-26'),
        items: [{ description: 'DevOps Kubernetes Automation Cluster', quantity: 1, unitPrice: 14500, amount: 14500 }],
        subtotal: 14500,
        tax: 0,
        totalAmount: 14500,
        amountPaid: 0,
        balanceDue: 14500,
        status: 'disputed',
        riskScore: 82,
        riskLevel: 'Critical',
        riskFactors: ['Duplicate billing sequence matching INV-2026-2004'],
        paymentTerms: 'Net 30',
      },
      {
        invoiceNumber: 'INV-2026-2004',
        type: 'payable',
        vendorName: 'Apex Cloud Systems LLC',
        department: 'Engineering',
        issueDate: new Date('2026-09-27'),
        dueDate: new Date('2026-10-27'),
        items: [{ description: 'DevOps Kubernetes Automation Cluster (Duplicate)', quantity: 1, unitPrice: 14500, amount: 14500 }],
        subtotal: 14500,
        tax: 0,
        totalAmount: 14500,
        amountPaid: 0,
        balanceDue: 14500,
        status: 'disputed',
        riskScore: 82,
        riskLevel: 'Critical',
        riskFactors: ['Duplicate invoice collision with INV-2026-2003'],
      },
      {
        invoiceNumber: 'INV-2026-2005',
        type: 'payable',
        vendorName: 'WeWork Global Spaces',
        department: 'Operations',
        issueDate: new Date('2026-09-01'),
        dueDate: new Date('2026-09-15'),
        items: [{ description: 'San Francisco & NYC Corporate Office Leases', quantity: 1, unitPrice: 14500, amount: 14500 }],
        subtotal: 14500,
        tax: 0,
        totalAmount: 14500,
        amountPaid: 14500,
        balanceDue: 0,
        status: 'paid',
        paymentHistory: [{ paymentDate: new Date('2026-09-14'), amount: 14500, method: 'ACH', reference: 'ACH-11094' }],
      },
      {
        invoiceNumber: 'INV-2026-2006',
        type: 'payable',
        vendorName: 'Covington & Burling LLP',
        department: 'Legal',
        issueDate: new Date('2026-08-20'),
        dueDate: new Date('2026-10-05'),
        items: [{ description: 'Corporate Governance & Regulatory Advisory', quantity: 1, unitPrice: 16400, amount: 16400 }],
        subtotal: 16400,
        tax: 0,
        totalAmount: 16400,
        amountPaid: 0,
        balanceDue: 16400,
        status: 'sent',
      },
    ];

    const invoices = await Invoice.insertMany(invoicesData);
    console.log(`[Seed Engine] Created ${invoices.length} Invoices.`);

    // 9. Seed 125+ Realistic Transactions
    const transactionsData = [];
    let txnCounter = 1001;

    // A. Specific High-Risk / Suspicious Transactions (Anomalies)
    transactionsData.push(
      // Anomaly 1: Critical - Modified Bank Details + Spike + 02:41 AM Sunday
      {
        txnId: `TXN-2026-${txnCounter++}`,
        date: new Date('2026-09-29T02:41:00Z'),
        type: 'expense',
        category: 'IT Infrastructure',
        subcategory: 'Hardware Acceleration',
        description: 'NovaTech Digital - Expedited Node Infrastructure Shipment',
        department: 'Engineering',
        vendorName: 'NovaTech Digital Solutions',
        employeeName: 'Jonathan Reynolds',
        amount: 34800,
        paymentMethod: 'Wire Transfer',
        status: 'flagged',
        isAnomaly: true,
        riskScore: 88,
        riskLevel: 'Critical',
        riskFactors: [
          'Vendor banking coordinates altered 4 days prior without secondary confirmation',
          'Disbursement is 3.55x above vendor historical 90-day moving average ($4,200)',
          'Initiated at 02:41 AM on Sunday outside standard treasury clearing windows',
        ],
        detectionTypes: ['Unusual Amount', 'Unusual Time', 'Suspicious Vendor'],
        evidence: [
          'Bank routing updated from JPMorgan (021000021) to Wells Fargo (121000358) on Sept 25',
          'Amount $34,800 is 3.8 standard deviations above peer hardware expense mean',
          'Timestamp: 2026-09-29T02:41:00Z violates corporate ACH business hours protocol',
        ],
        recommendedAction: 'Freeze wire disbursement immediately; mandate direct phone confirmation with vendor CFO.',
        invoiceNumber: 'INV-2026-2002',
        bankAccountName: 'Operating Treasury',
        auditTrail: [
          { action: 'Ingested via Wire API', performedBy: 'System', timestamp: new Date('2026-09-29T02:41:00Z') },
          { action: 'AI Anomaly Flagged', performedBy: 'FinGuard Neural Engine', timestamp: new Date('2026-09-29T02:41:05Z'), notes: 'Risk Score 88/100 (Critical)' },
          { action: 'Automated Hold Applied', performedBy: 'Treasury Guard', timestamp: new Date('2026-09-29T02:41:06Z'), notes: 'Wire held in escrow queue' },
        ],
      },
      // Anomaly 2: Duplicate Payment ($14,500 issued twice within 24h)
      {
        txnId: `TXN-2026-${txnCounter++}`,
        date: new Date('2026-09-26T14:15:00Z'),
        type: 'expense',
        category: 'DevOps & Tooling',
        description: 'Apex Cloud Systems - DevOps Kubernetes Automation Cluster (Primary)',
        department: 'Engineering',
        vendorName: 'Apex Cloud Systems LLC',
        employeeName: 'David Kim',
        amount: 14500,
        paymentMethod: 'ACH',
        status: 'completed',
        isAnomaly: false,
        riskScore: 18,
        riskLevel: 'Low',
        invoiceNumber: 'INV-2026-2003',
      },
      {
        txnId: `TXN-2026-${txnCounter++}`,
        date: new Date('2026-09-27T11:05:00Z'),
        type: 'expense',
        category: 'DevOps & Tooling',
        description: 'Apex Cloud Systems - DevOps Kubernetes Automation Cluster (Duplicate Collision)',
        department: 'Engineering',
        vendorName: 'Apex Cloud Systems LLC',
        employeeName: 'David Kim',
        amount: 14500,
        paymentMethod: 'ACH',
        status: 'under_review',
        isAnomaly: true,
        riskScore: 82,
        riskLevel: 'Critical',
        riskFactors: [
          'Exact amount duplicate ($14,500) to identical vendor within 21 hours',
          'Reference invoice text matches prior completed disbursement',
        ],
        detectionTypes: ['Duplicate Payment', 'Repeated Payment'],
        evidence: [
          'Collision detected with completed transaction TXN-2026-1002 ($14,500.00)',
          'Identical recipient bank account •••• 3341',
        ],
        recommendedAction: 'Hold payment run; request vendor accounts receivable to issue credit note or cancel duplicate ticket.',
        invoiceNumber: 'INV-2026-2004',
      },
      // Anomaly 3: Structured / Split Transaction ($4,950 & $4,980 to stay below $5,000 threshold)
      {
        txnId: `TXN-2026-${txnCounter++}`,
        date: new Date('2026-09-24T16:20:00Z'),
        type: 'expense',
        category: 'IT Procurement',
        description: 'Batch Workstation Monitors & Docks - Part A',
        department: 'Operations & IT',
        employeeName: 'Bradley Cooper',
        amount: 4950,
        paymentMethod: 'Corporate Card',
        status: 'under_review',
        isAnomaly: true,
        riskScore: 76,
        riskLevel: 'High',
        riskFactors: ['Amount ($4,950) structured $50 immediately below $5,000 supervisor authorization rule'],
        detectionTypes: ['Split Transaction'],
        evidence: [
          'Transaction amount is 99.0% of the $5,000 procurement signoff limit',
          'Followed by second charge of $4,980 within 90 minutes',
        ],
        recommendedAction: 'Combine vouchers into single requisition for VP Operations approval.',
      },
      {
        txnId: `TXN-2026-${txnCounter++}`,
        date: new Date('2026-09-24T17:45:00Z'),
        type: 'expense',
        category: 'IT Procurement',
        description: 'Batch Workstation Monitors & Docks - Part B',
        department: 'Operations & IT',
        employeeName: 'Bradley Cooper',
        amount: 4980,
        paymentMethod: 'Corporate Card',
        status: 'under_review',
        isAnomaly: true,
        riskScore: 78,
        riskLevel: 'High',
        riskFactors: ['Amount ($4,980) structured $20 below $5,000 approval limit'],
        detectionTypes: ['Split Transaction'],
        evidence: [
          'Immediate companion purchase to TXN-2026-1004 from same employee card within 85 minutes',
        ],
        recommendedAction: 'Require combined $9,930 requisition review.',
      },
      // Anomaly 4: Spending Spike to Marketing Agency
      {
        txnId: `TXN-2026-${txnCounter++}`,
        date: new Date('2026-09-22T19:10:00Z'),
        type: 'expense',
        category: 'Marketing',
        description: 'Vanguard Media - Unplanned Influencer Campaign Retainer',
        department: 'Sales & Marketing',
        vendorName: 'Vanguard Media & Growth',
        employeeName: 'Rachel Green',
        amount: 28400,
        paymentMethod: 'ACH',
        status: 'under_review',
        isAnomaly: true,
        riskScore: 68,
        riskLevel: 'High',
        riskFactors: [
          'Vendor billing velocity is 3.1x higher than quarterly moving average ($9,100)',
          'Pushes Sales & Marketing department 108% over approved quarterly budget ceiling',
        ],
        detectionTypes: ['Spending Spike', 'Behavioral Anomaly'],
        evidence: [
          'Baseline monthly billing: $9,160 ± $1,800; Current charge: $28,400',
          'Department allocation remaining before charge: -$10,500',
        ],
        recommendedAction: 'Obtain CFO variance signoff before releasing ACH clearing batch.',
      },
      // Anomaly 5: Disproportionate Abnormal Refund
      {
        txnId: `TXN-2026-${txnCounter++}`,
        date: new Date('2026-09-18T10:14:00Z'),
        type: 'refund',
        category: 'Customer Credits',
        description: 'Manual Balance Refund to Overseas Account',
        department: 'Finance',
        customerName: 'Silverline Media',
        employeeName: 'Sarah Chen',
        amount: 9800,
        paymentMethod: 'Wire Transfer',
        status: 'under_review',
        isAnomaly: true,
        riskScore: 72,
        riskLevel: 'High',
        riskFactors: ['Manual refund issued without matching original deposit or verified credit memo'],
        detectionTypes: ['Abnormal Refund'],
        evidence: [
          'No corresponding $9,800 debit transaction identified in prior 90 days of general ledger',
          'Destination account differs from established customer billing profile',
        ],
        recommendedAction: 'Verify original deposit remittance advice with commercial bank partner.',
      },
      // Anomaly 6: Behavioral Anomaly - Travel Luxury Hotel
      {
        txnId: `TXN-2026-${txnCounter++}`,
        date: new Date('2026-09-20T23:15:00Z'),
        type: 'expense',
        category: 'Travel & Entertainment',
        description: 'Global Executive Travel - Luxury Penthouse Suite Weekend',
        department: 'Sales & Marketing',
        vendorName: 'Global Executive Travel Corp',
        employeeName: 'Rachel Green',
        amount: 6850,
        paymentMethod: 'Corporate Card',
        status: 'under_review',
        isAnomaly: true,
        riskScore: 64,
        riskLevel: 'High',
        riskFactors: ['Exceeds employee monthly spend limit and corporate travel per-diem policy'],
        detectionTypes: ['Behavioral Anomaly', 'Unusual Amount'],
        evidence: [
          'Nightly rate of $2,280 violates corporate lodging cap of $350/night',
          'Expense submitted over weekend outside approved business travel schedule',
        ],
        recommendedAction: 'Flag for VP review and employee reimbursement deduction if unapproved.',
      }
    );

    // B. Generate 115+ Normal, Healthy, Believable Corporate Transactions
    const expenseTemplates = [
      { vendor: 'Amazon Web Services Inc.', cat: 'Cloud Infrastructure', dept: 'Engineering', desc: 'AWS EC2 & S3 Cloud Usage', min: 8000, max: 18000, method: 'ACH' },
      { vendor: 'Datadog Inc.', cat: 'Software & SaaS', dept: 'Engineering', desc: 'APM Infrastructure Monitoring Subscription', min: 4500, max: 6200, method: 'ACH' },
      { vendor: 'Google Workspace & Cloud', cat: 'Software & SaaS', dept: 'Operations & IT', desc: 'Google Enterprise Workspace Licenses', min: 2800, max: 3500, method: 'ACH' },
      { vendor: 'Slack Technologies', cat: 'Software & SaaS', dept: 'Operations & IT', desc: 'Corporate Slack Enterprise Grid', min: 3800, max: 4200, method: 'ACH' },
      { vendor: 'WeWork Global Spaces', cat: 'Facilities & Rent', dept: 'Operations & IT', desc: 'Monthly Office Space Lease & Utilities', min: 14000, max: 15000, method: 'Wire Transfer' },
      { vendor: 'Covington & Burling LLP', cat: 'Legal & Professional', dept: 'Legal & Compliance', desc: 'Corporate Legal Retainer & IP Filing', min: 12000, max: 20000, method: 'Wire Transfer' },
      { vendor: 'Kroll Cyber Security', cat: 'Security & Audit', dept: 'Legal & Compliance', desc: 'Annual SOC2 Audit & Penetration Testing', min: 15000, max: 18000, method: 'Wire Transfer' },
      { vendor: 'Pivotal Talent Recruitment', cat: 'Human Resources', dept: 'Human Resources', desc: 'Executive Search & Placement Fees', min: 10000, max: 14000, method: 'ACH' },
      { vendor: 'Stripe Corporate Billing', cat: 'Financial Services', dept: 'Finance', desc: 'Payment Gateway Processing Charges', min: 1800, max: 2800, method: 'ACH' },
      { vendor: 'Catering & Executive Events Co', cat: 'Office & Hospitality', dept: 'Operations & IT', desc: 'All-Hands Catering & Team Dinners', min: 1200, max: 2800, method: 'Corporate Card' },
      { vendor: 'FedEx Corporate Logistics', cat: 'Logistics & Shipping', dept: 'Operations & IT', desc: 'Hardware Logistics & Express Shipping', min: 800, max: 1600, method: 'Corporate Card' },
      { vendor: 'Global Executive Travel Corp', cat: 'Travel & Entertainment', dept: 'Sales & Marketing', desc: 'Commercial Flight & Hotel - Client Onsite', min: 1200, max: 2500, method: 'Corporate Card' },
    ];

    const customerTemplates = [
      { cust: 'CyberScale Corp', desc: 'Enterprise SaaS Annual Renewal', min: 35000, max: 65000 },
      { cust: 'Horizon FinTech Group', desc: 'FinTech Platform Transaction Volume Fee', min: 25000, max: 55000 },
      { cust: 'Nexus Dynamics', desc: 'Machine Learning Infrastructure Billing', min: 20000, max: 40000 },
      { cust: 'Vortex Capital Partners', desc: 'Quarterly Risk Surveillance Contract', min: 45000, max: 80000 },
      { cust: 'Quantum Logic Systems', desc: 'Telemetry API Connector Licensing', min: 15000, max: 30000 },
      { cust: 'Solaria Energy Technologies', desc: 'Enterprise Security Suite Deployment', min: 22000, max: 38000 },
    ];

    const empNames = ['David Kim', 'Rachel Green', 'Jessica Miller', 'Jonathan Reynolds', 'Bradley Cooper', 'Sophia Laurent', 'Claire Bennett', 'Marcus Sterling'];

    // Generate transactions over the past 90 days
    const nowMs = Date.now();
    for (let i = 0; i < 118; i++) {
      const daysAgo = Math.floor(Math.random() * 88);
      const txnDate = new Date(nowMs - daysAgo * 24 * 60 * 60 * 1000 - Math.floor(Math.random() * 8) * 3600 * 1000);
      const isIncome = Math.random() < 0.28; // 28% income, 72% expense/transfer

      if (isIncome) {
        const tmpl = customerTemplates[Math.floor(Math.random() * customerTemplates.length)];
        const amount = Math.floor(Math.random() * (tmpl.max - tmpl.min) + tmpl.min);
        transactionsData.push({
          txnId: `TXN-2026-${txnCounter++}`,
          date: txnDate,
          type: 'income',
          category: 'Operating Revenue',
          subcategory: 'SaaS Subscription',
          description: `${tmpl.cust} - ${tmpl.desc}`,
          department: 'Sales & Marketing',
          customerName: tmpl.cust,
          amount,
          paymentMethod: Math.random() > 0.4 ? 'ACH' : 'Wire Transfer',
          status: 'completed',
          isAnomaly: false,
          riskScore: Math.floor(Math.random() * 12) + 2,
          riskLevel: 'Low',
          bankAccountName: 'Operating Treasury',
        });
      } else {
        const tmpl = expenseTemplates[Math.floor(Math.random() * expenseTemplates.length)];
        const amount = Math.floor(Math.random() * (tmpl.max - tmpl.min) + tmpl.min);
        const emp = empNames[Math.floor(Math.random() * empNames.length)];
        const isRecurring = ['AWS Cloud Hosting', 'Slack Enterprise Grid', 'Google Enterprise Workspace Licenses', 'Monthly Office Space Lease & Utilities'].some((k) => tmpl.desc.includes(k));

        transactionsData.push({
          txnId: `TXN-2026-${txnCounter++}`,
          date: txnDate,
          type: 'expense',
          category: tmpl.cat,
          subcategory: 'Operational Expense',
          description: `${tmpl.vendor} - ${tmpl.desc}`,
          department: tmpl.dept,
          vendorName: tmpl.vendor,
          employeeName: emp,
          amount,
          paymentMethod: tmpl.method,
          status: 'completed',
          isAnomaly: false,
          riskScore: Math.floor(Math.random() * 18) + 4,
          riskLevel: 'Low',
          isRecurring,
          recurringInterval: isRecurring ? 'Monthly' : 'None',
          bankAccountName: tmpl.method === 'Wire Transfer' ? 'Operating Treasury' : 'Payroll Clearing Account',
        });
      }
    }

    const transactions = await Transaction.insertMany(transactionsData);
    console.log(`[Seed Engine] Created ${transactions.length} Transactions.`);

    // 10. Seed Fraud Alerts (Matching the anomalous transactions)
    const fraudAlertsData = [
      {
        alertId: 'ALT-9901',
        txnId: 'TXN-2026-1001',
        entityType: 'Vendor',
        entityName: 'NovaTech Digital Solutions',
        amount: 34800,
        riskScore: 88,
        riskLevel: 'Critical',
        detectionType: 'Suspicious Vendor',
        detectionDate: new Date('2026-09-29T02:41:00Z'),
        status: 'Under Review',
        reasons: [
          'Vendor banking coordinates altered 4 days prior without secondary confirmation',
          'Disbursement is 3.55x above vendor historical 90-day moving average ($4,200)',
          'Initiated at 02:41 AM on Sunday outside standard treasury clearing windows',
        ],
        evidence: [
          'Bank routing updated from JPMorgan (021000021) to Wells Fargo (121000358) on Sept 25',
          'Amount $34,800 is 3.8 standard deviations above peer hardware expense mean',
          'Timestamp: 2026-09-29T02:41:00Z violates corporate ACH business hours protocol',
        ],
        relatedTransactionIds: ['TXN-2026-1001'],
        recommendedAction: 'Freeze wire disbursement immediately; mandate direct phone confirmation with vendor CFO.',
        assignedTo: 'Elena Rostova (Lead Fraud Analyst)',
      },
      {
        alertId: 'ALT-9902',
        txnId: 'TXN-2026-1003',
        entityType: 'Vendor',
        entityName: 'Apex Cloud Systems LLC',
        amount: 14500,
        riskScore: 82,
        riskLevel: 'Critical',
        detectionType: 'Duplicate Payment',
        detectionDate: new Date('2026-09-27T11:05:00Z'),
        status: 'Under Review',
        reasons: [
          'Exact duplicate amount ($14,500) issued to same payee within 21 hours of completed voucher',
          'Reference invoice text matches prior completed disbursement',
        ],
        evidence: [
          'Collision detected with completed transaction TXN-2026-1002 ($14,500.00)',
          'Identical recipient bank account •••• 3341',
        ],
        relatedTransactionIds: ['TXN-2026-1002', 'TXN-2026-1003'],
        recommendedAction: 'Hold payment run; request vendor accounts receivable to issue credit note or cancel duplicate ticket.',
        assignedTo: 'Elena Rostova (Lead Fraud Analyst)',
      },
      {
        alertId: 'ALT-9903',
        txnId: 'TXN-2026-1004',
        entityType: 'Employee',
        entityName: 'Bradley Cooper',
        amount: 4950,
        riskScore: 76,
        riskLevel: 'High',
        detectionType: 'Split Transaction',
        detectionDate: new Date('2026-09-24T16:20:00Z'),
        status: 'Escalated',
        reasons: ['Structured purchase amount ($4,950) immediately below mandatory $5,000 supervisor threshold'],
        evidence: [
          'Followed by companion charge of $4,980 from same card within 85 minutes',
          'Total unapproved procurement: $9,930',
        ],
        relatedTransactionIds: ['TXN-2026-1004', 'TXN-2026-1005'],
        recommendedAction: 'Combine vouchers into single requisition for VP Operations approval.',
        assignedTo: 'Marcus Sterling',
      },
      {
        alertId: 'ALT-9904',
        txnId: 'TXN-2026-1006',
        entityType: 'Vendor',
        entityName: 'Vanguard Media & Growth',
        amount: 28400,
        riskScore: 68,
        riskLevel: 'High',
        detectionType: 'Spending Spike',
        detectionDate: new Date('2026-09-22T19:10:00Z'),
        status: 'New',
        reasons: ['Vendor expenditure velocity increased 310% compared with 90-day moving average baseline'],
        evidence: [
          'Historical 90-day vendor average: $9,160 ± $1,800; Current charge: $28,400',
          'Pushes Sales & Marketing department 108% over approved quarterly budget ceiling',
        ],
        relatedTransactionIds: ['TXN-2026-1006'],
        recommendedAction: 'Obtain CFO variance signoff before releasing ACH clearing batch.',
      },
      {
        alertId: 'ALT-9905',
        txnId: 'TXN-2026-1007',
        entityType: 'Customer',
        entityName: 'Silverline Media',
        amount: 9800,
        riskScore: 72,
        riskLevel: 'High',
        detectionType: 'Abnormal Refund',
        detectionDate: new Date('2026-09-18T10:14:00Z'),
        status: 'New',
        reasons: ['Manual refund issued without matching original deposit or verified credit memo'],
        evidence: [
          'No corresponding $9,800 debit transaction identified in prior 90 days of general ledger',
          'Destination account differs from established customer billing profile',
        ],
        relatedTransactionIds: ['TXN-2026-1007'],
        recommendedAction: 'Verify original deposit remittance advice with commercial bank partner.',
      },
      {
        alertId: 'ALT-9906',
        txnId: 'TXN-2026-1008',
        entityType: 'Employee',
        entityName: 'Rachel Green',
        amount: 6850,
        riskScore: 64,
        riskLevel: 'High',
        detectionType: 'Behavioral Anomaly',
        detectionDate: new Date('2026-09-20T23:15:00Z'),
        status: 'Under Review',
        reasons: ['Expense claims violate corporate per-diem caps and exceed monthly allowance'],
        evidence: [
          'Nightly rate of $2,280 violates corporate lodging cap of $350/night',
          'Expense submitted over weekend outside approved business travel schedule',
        ],
        relatedTransactionIds: ['TXN-2026-1008'],
        recommendedAction: 'Flag for VP review and employee reimbursement deduction if unapproved.',
        assignedTo: 'Alex Vance',
      },
      {
        alertId: 'ALT-9907',
        txnId: 'TXN-2026-1015',
        entityType: 'Vendor',
        entityName: 'Catering & Executive Events Co',
        amount: 2800,
        riskScore: 32,
        riskLevel: 'Medium',
        detectionType: 'Unusual Amount',
        detectionDate: new Date('2026-09-15T12:00:00Z'),
        status: 'Resolved',
        reasons: ['Quarterly team all-hands dinner exceeded standard monthly hospitality average'],
        evidence: ['Receipt attached; authorized by Head of People for company celebration'],
        relatedTransactionIds: ['TXN-2026-1015'],
        recommendedAction: 'Approved under special events budget line.',
        resolutionNotes: 'Verified receipt and guest list. Legitimate company event.',
      },
      {
        alertId: 'ALT-9908',
        txnId: 'TXN-2026-1022',
        entityType: 'Vendor',
        entityName: 'NovaTech Digital Solutions',
        amount: 14900,
        riskScore: 74,
        riskLevel: 'High',
        detectionType: 'Invoice Anomaly',
        detectionDate: new Date('2026-09-12T16:00:00Z'),
        status: 'Confirmed Fraud',
        reasons: ['Invoiced for hardware serial numbers that failed warehouse physical receipt scan'],
        evidence: ['Warehouse inventory audit report #WH-882 confirms zero hardware delivered'],
        relatedTransactionIds: ['TXN-2026-1022'],
        recommendedAction: 'Block vendor profile; initiate legal recovery through outside counsel.',
        assignedTo: 'Elena Rostova (Lead Fraud Analyst)',
        resolutionNotes: 'Confirmed phantom billing. Vendor blocked and case submitted to legal.',
      },
    ];

    const fraudAlerts = await FraudAlert.insertMany(fraudAlertsData);
    console.log(`[Seed Engine] Created ${fraudAlerts.length} Fraud Alerts.`);

    // 11. Seed Investigations
    const investigationsData = [
      {
        caseId: 'CASE-2026-0081',
        title: 'NovaTech Digital Solutions: Unauthorized Routing Alteration & Surge Disbursement',
        txnId: 'TXN-2026-1001',
        entityType: 'Vendor',
        entityName: 'NovaTech Digital Solutions',
        amountExposed: 34800,
        riskScore: 88,
        riskLevel: 'Critical',
        status: 'Under Review',
        priority: 'Critical',
        assignedInvestigator: 'Elena Rostova (Lead Fraud Analyst)',
        investigatorEmail: 'elena.rostova@finguard.internal',
        caseSummary: 'Automated telemetry flagged an attempted $34,800 wire disbursement to NovaTech Solutions. Banking coordinates were changed 4 days prior to a newly opened Wells Fargo account without dual verification, and the amount represents a 355% surge over historical baseline.',
        aiAnalysisSummary: 'FinGuard Neural Engine calculated a multi-signal risk rating of 88/100. Primary flags: Vendor account details were recently modified; Transaction is significantly above vendor historical average; Payment timing (02:41 AM Sunday) violates normal treasury patterns.',
        detectedFactors: [
          'Transaction amount ($34,800) is 3.55x above historical supplier average',
          'Beneficiary account details were updated 4 calendar days ago',
          'Disbursement initiated outside normal business operating hours (Sunday 02:41 AM)',
          'No corresponding approved purchase order in procurement database',
        ],
        recommendedReview: 'Verify physical invoice and conduct live voice verification with vendor CFO before authorizing payment release.',
        relatedTransactions: [
          { txnId: 'TXN-2026-1001', date: new Date('2026-09-29T02:41:00Z'), amount: 34800, type: 'expense', status: 'flagged', riskScore: 88, similarityFactor: 'Primary flagged item' },
          { txnId: 'TXN-2026-1022', date: new Date('2026-09-12T16:00:00Z'), amount: 14900, type: 'expense', status: 'rejected', riskScore: 74, similarityFactor: 'Prior rejected phantom invoice' },
        ],
        timeline: [
          { date: new Date('2026-09-25T11:20:00Z'), title: 'Vendor Banking Coordinates Modified', description: 'Routing number changed from JPMorgan to Wells Fargo in supplier portal.', user: 'Supplier Portal Admin', icon: 'edit' },
          { date: new Date('2026-09-29T02:41:00Z'), title: 'Suspicious Wire Batch Submitted', description: 'Wire transfer $34,800 queued for clearing.', user: 'Automated Ingestion', icon: 'zap' },
          { date: new Date('2026-09-29T02:41:05Z'), title: 'FinGuard AI Anomaly Triggered', description: 'Risk Score 88/100 computed. Payment frozen automatically.', user: 'FinGuard AI', icon: 'shield-alert' },
          { date: new Date('2026-09-29T08:30:00Z'), title: 'Forensic Case Assigned', description: 'Assigned to Elena Rostova for vendor direct validation.', user: 'Marcus Sterling', icon: 'user' },
        ],
        evidence: [
          { id: 'EV-1', title: 'Portal Audit Log: Bank Details Alteration', type: 'Log', notes: 'IP 185.220.101.4 (Known VPN exit node) altered bank account details on Sept 25.' },
          { id: 'EV-2', title: 'Historical Billing Variance Chart', type: 'Comparison', notes: 'Supplier 90-day moving average was $4,200 vs current $34,800 invoice.' },
          { id: 'EV-3', title: 'Invoice PDF Document Analysis', type: 'Document', notes: 'Metadata indicates PDF created with non-standard tools 1 hour prior to submission.' },
        ],
        investigatorNotes: [
          { author: 'Elena Rostova', role: 'Fraud Analyst', text: 'Contacted vendor listed primary contact by verified corporate phone. Their billing team denies submitting invoice INV-2026-2002.', createdAt: new Date('2026-09-29T10:15:00Z') },
          { author: 'Marcus Sterling', role: 'Treasury Director', text: 'Treasury payment rail confirmed locked. Zero capital cleared outside the institution.', createdAt: new Date('2026-09-29T11:00:00Z') },
        ],
        auditTrail: [
          { action: 'Case Created', user: 'System', timestamp: new Date('2026-09-29T08:30:00Z'), details: 'Automated escalation from Alert ALT-9901' },
          { action: 'Disbursement Hold Applied', user: 'Marcus Sterling', timestamp: new Date('2026-09-29T08:35:00Z'), details: 'Wire hold confirmed' },
        ],
      },
      {
        caseId: 'CASE-2026-0082',
        title: 'Apex Cloud Systems: Identical $14,500 Duplicate Payment Collision',
        txnId: 'TXN-2026-1003',
        entityType: 'Vendor',
        entityName: 'Apex Cloud Systems LLC',
        amountExposed: 14500,
        riskScore: 82,
        riskLevel: 'Critical',
        status: 'Under Review',
        priority: 'High',
        assignedInvestigator: 'Elena Rostova (Lead Fraud Analyst)',
        investigatorEmail: 'elena.rostova@finguard.internal',
        caseSummary: 'Two identical disbursements of $14,500 were submitted for the same Kubernetes automation cluster within 21 hours. The secondary transaction was held to prevent duplicate cash drainage.',
        aiAnalysisSummary: 'FinGuard Duplicate Engine detected exact match on amount ($14,500.00), payee vendor ID, and invoice line items. High risk rating (82/100).',
        detectedFactors: [
          'Duplicate billing identified: $14,500 invoiced twice within 24 hours',
          'Voucher line items and purchase descriptions are 100% identical',
        ],
        recommendedReview: 'Hold payment run; request vendor AR to issue formal credit confirmation before releasing any funds.',
        timeline: [
          { date: new Date('2026-09-26T14:15:00Z'), title: 'Primary Invoice Cleared', description: 'Voucher $14,500 approved and cleared via ACH.', user: 'Sarah Chen', icon: 'check' },
          { date: new Date('2026-09-27T11:05:00Z'), title: 'Duplicate Voucher Submitted', description: 'Duplicate $14,500 voucher submitted via automated ERP sync.', user: 'System', icon: 'copy' },
          { date: new Date('2026-09-27T11:05:04Z'), title: 'Duplicate Hold Triggered', description: 'FinGuard blocked settlement execution.', user: 'FinGuard AI', icon: 'pause' },
        ],
        evidence: [
          { id: 'EV-1', title: 'Invoice Side-by-Side Comparison', type: 'Comparison', notes: 'INV-2026-2003 and INV-2026-2004 have identical item text and tax calculations.' },
        ],
        investigatorNotes: [
          { author: 'Elena Rostova', role: 'Fraud Analyst', text: 'Vendor AR confirmed an automated billing glitch on their Stripe Billing connector resent the invoice twice. Voiding duplicate voucher.', createdAt: new Date('2026-09-28T09:30:00Z') },
        ],
        auditTrail: [
          { action: 'Case Opened', user: 'System', timestamp: new Date('2026-09-27T11:05:00Z'), details: 'Alert ALT-9902 promoted to investigation' },
        ],
      },
      {
        caseId: 'CASE-2026-0083',
        title: 'IT Procurement: Consecutive Transactions Structured Below $5,000 Threshold',
        txnId: 'TXN-2026-1004',
        entityType: 'Employee',
        entityName: 'Bradley Cooper',
        amountExposed: 9930,
        riskScore: 76,
        riskLevel: 'High',
        status: 'Open',
        priority: 'High',
        assignedInvestigator: 'Marcus Sterling',
        caseSummary: 'Identified consecutive purchasing card transactions of $4,950 and $4,980 within 85 minutes. Circumvents internal policy requiring VP pre-approval on any hardware requisition of $5,000+.',
        aiAnalysisSummary: 'Structuring detection pattern matched: Multiple micro-transactions just below executive threshold ($5,000) totaling $9,930.',
        detectedFactors: [
          'Transaction 1: $4,950 (99.0% of limit)',
          'Transaction 2: $4,980 (99.6% of limit)',
          'Time difference: 85 minutes',
        ],
        recommendedReview: 'Consolidate into single $9,930 requisition and obtain formal VP Operations approval.',
        timeline: [
          { date: new Date('2026-09-24T16:20:00Z'), title: 'Part A Charge Recorded', description: '$4,950 charged on corporate card.', user: 'Bradley Cooper', icon: 'credit-card' },
          { date: new Date('2026-09-24T17:45:00Z'), title: 'Part B Charge Recorded', description: '$4,980 charged on corporate card.', user: 'Bradley Cooper', icon: 'credit-card' },
          { date: new Date('2026-09-24T17:46:00Z'), title: 'Structuring Anomaly Flagged', description: 'Algorithm correlated both disbursements.', user: 'FinGuard AI', icon: 'alert' },
        ],
        evidence: [
          { id: 'EV-1', title: 'Card Transaction Stream Log', type: 'Log', notes: 'Merchant terminal matches same vendor within 85 minute interval.' },
        ],
        investigatorNotes: [
          { author: 'Marcus Sterling', role: 'Treasury Director', text: 'Sent formal policy reminder to procurement lead; requested consolidated approval invoice.', createdAt: new Date('2026-09-25T09:00:00Z') },
        ],
        auditTrail: [
          { action: 'Case Created', user: 'System', timestamp: new Date('2026-09-24T17:46:00Z'), details: 'Alert ALT-9903 escalated' },
        ],
      },
    ];

    const investigations = await Investigation.insertMany(investigationsData);
    console.log(`[Seed Engine] Created ${investigations.length} Investigations.`);

    // 12. Seed Audit Logs
    const auditLogsData = [
      {
        userName: 'Alex Vance',
        userEmail: 'alex.vance@finguard.internal',
        userRole: 'Super Admin',
        action: 'System Configuration Updated',
        module: 'Settings',
        recordId: 'CFG-2026',
        recordType: 'SystemConfig',
        newValue: { fraudThreshold: 60, dualApprovalLimit: 25000 },
        details: 'Updated global fraud scoring sensitivity to High and lowered dual approval ceiling to $25k.',
        timestamp: new Date('2026-09-30T10:00:00Z'),
      },
      {
        userName: 'Elena Rostova',
        userEmail: 'elena.rostova@finguard.internal',
        userRole: 'Fraud Analyst',
        action: 'Disbursement Placed on Hold',
        module: 'Fraud Detection',
        recordId: 'TXN-2026-1001',
        recordType: 'Transaction',
        previousValue: { status: 'pending' },
        newValue: { status: 'flagged' },
        details: 'Placed $34,800 wire to NovaTech Digital on hold due to banking coordinate change.',
        timestamp: new Date('2026-09-29T02:41:06Z'),
      },
      {
        userName: 'Marcus Sterling',
        userEmail: 'marcus.sterling@finguard.internal',
        userRole: 'Finance Manager',
        action: 'Budget Reallocation Approved',
        module: 'Budgets',
        recordId: 'BUD-ENG-Q3',
        recordType: 'Budget',
        previousValue: { allocatedAmount: 320000 },
        newValue: { allocatedAmount: 350000 },
        details: 'Approved $30,000 increase for Engineering EU cloud compliance cluster.',
        timestamp: new Date('2026-09-28T14:30:00Z'),
      },
      {
        userName: 'Sarah Chen',
        userEmail: 'sarah.chen@finguard.internal',
        userRole: 'Accountant',
        action: 'Invoice Approved & Reconciled',
        module: 'Invoices',
        recordId: 'INV-2026-2005',
        recordType: 'Invoice',
        previousValue: { status: 'sent' },
        newValue: { status: 'paid' },
        details: 'Reconciled WeWork office space lease payment of $14,500.',
        timestamp: new Date('2026-09-14T11:10:00Z'),
      },
      {
        userName: 'David Kim',
        userEmail: 'david.kim@finguard.internal',
        userRole: 'Department Manager',
        action: 'Purchase Order Authorized',
        module: 'Transactions',
        recordId: 'TXN-2026-1002',
        recordType: 'Transaction',
        newValue: { amount: 14500, vendor: 'Apex Cloud Systems LLC' },
        details: 'Department manager signoff for Kubernetes automation cluster.',
        timestamp: new Date('2026-09-26T14:00:00Z'),
      },
    ];

    const auditLogs = await AuditLog.insertMany(auditLogsData);
    console.log(`[Seed Engine] Created ${auditLogs.length} Audit Logs.`);

    console.log('----------------------------------------------------');
    console.log('✅ FinGuard AI Database Successfully Seeded!');
    console.log(`   - Users: ${users.length}`);
    console.log(`   - Departments: ${departments.length}`);
    console.log(`   - Bank Accounts: ${bankAccounts.length}`);
    console.log(`   - Employees: ${employees.length}`);
    console.log(`   - Vendors: ${vendors.length}`);
    console.log(`   - Customers: ${customers.length}`);
    console.log(`   - Budgets: ${budgets.length}`);
    console.log(`   - Invoices: ${invoices.length}`);
    console.log(`   - Transactions: ${transactions.length}`);
    console.log(`   - Fraud Alerts: ${fraudAlerts.length}`);
    console.log(`   - Investigations: ${investigations.length}`);
    console.log(`   - Audit Logs: ${auditLogs.length}`);
    console.log('----------------------------------------------------');

    process.exit(0);
  } catch (error) {
    console.error('❌ [Seed Engine Error]:', error);
    process.exit(1);
  }
};

seedDatabase();
